### ISSUE TITLE
1.16.5刷沙报错

### ISSUE THREAD

**Issue by Nobi-kamo** [neko-craft/NekoAgent#3]
paper-1.16.5
正常安装,正常配置
结果:后台报错,无法刷沙,其他特性未尝试
相关logs:
[NekoAgent] Class BlockStonecutter has been modified!
[NekoAgent] Class WorldServer has been modified!
[NekoAgent] Class EntityPlayer has been modified!
[NekoAgent] Class EntityFallingBlock has been modified!
javassist.NotFoundException: a(..) is not found in net.minecraft.server.v1_16_R3.WorldGenEnder
        at javassist.CtClassType.getMethod(CtClassType.java:1262)
        at cn.apisium.nekoagent.Main$Transformer.transform(Main.java:97)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:565)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.minecraft.server.v1_16_R3.BiomeDecoratorGroups.<clinit>(SourceFile:92)
        at net.minecraft.server.v1_16_R3.RegistryGeneration.lambda$static$2(RegistryGeneration.java:43)
        at net.minecraft.server.v1_16_R3.RegistryGeneration.lambda$static$8(RegistryGeneration.java:90)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
        at net.minecraft.server.v1_16_R3.RegistryGeneration.<clinit>(RegistryGeneration.java:89)
        at net.minecraft.server.v1_16_R3.IRegistry.<clinit>(IRegistry.java:439)
        at net.minecraft.server.v1_16_R3.DispenserRegistry.init(DispenserRegistry.java:44)
        at net.minecraft.server.v1_16_R3.Main.main(Main.java:100)
        at org.bukkit.craftbukkit.Main.main(Main.java:289)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:58)
[14:05:22 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

**Comment by ShirasawaSama** [comment]
1.16.5已经不再支持 请更新至1.17

**Comment by ShirasawaSama** [comment]
并且你这是潜影盒再生功能的报错
